### ISSUE TITLE
Order of the libraries to be tested

### ISSUE THREAD

**Issue by Frogli** [suransys/omniscli#3]
In the danger that I am answering my own question I still want to post it here. Maybe there is a better solution.

I have been testing OmnisCLI with OmnisTAP and run up a problem when the test library is loaded before the OmnisCLI and OmnisTAP library. An error is shown that OmnisCLI is not available. A simple solution is to rename the test library and also the production library if it is separate. The only thing I run up there is that hardcoded references to the test or production library are not working anymore. 

Would there be a more elegant way to deal with this?

**Comment by omnis-ninja** [comment]
I think @omnis-jedi should also weigh in on this.
But, I easily found a fix for this and in doing so I think its a bug.

- When you copy omniscli and omnistap to your startup folder and fire omnis up, 
  - omniscli gets loaded first, 
  - and then omnistap library gets launched.
- Classic chicken <-> egg scenario plays out. 
  - Omniscli.Startup_Task is dependant on the omnistap.kgTapTask, but omnistap isn't loaded up so it wont inherit anything and omnis wont complain. 
  - omnistap library then gets launched and its Startup_Task is fired up.
  - But the omniscli task is still the same, unless its relaunched, which will properly construct it (with inheritance), its inherited methods wont be active.

Now if you try to run a test on the omniscli library, it will fail at wgOmnisTap.$_getTaskForTesting line# 8. Why? because the omniscli library's Startup_Task didn't construct properly since omnistap library at that time wasn't available. 

So, to remedy this, modify omnistap.Startup_Task we test to see if the omniscli is loaded and if so relaunch it. that takes care of the inheritance issue from omniscli's perspective.

Not sure if this qualifies as a bug or not.

Another issue I found is in omnistap.k1Super, it inherits kgTapTask, but it never "instantiates" its construct or the inheritance is broken. This can be easily seen when you hover over the uoLog task variable, its not constructed.

Now I have the omnistap library patched up in my library and will post my changes to this repo if @omnis-jedi approves them.

**Comment by barkingfoodog** [comment]
@Frogli the way we handle this is to deploy `omnisci.lbs` and `omnistap.lbs` outside the startup folder. When our application library launches, one of the first things it does is to opens these libraries. This ensures everything is loaded in the right order

Another solution is to use the https://github.com/PISL/omnis-launcher project and specify your library's load order.

However, I want to be sure I know exactly what you're running into. Are you looking to add tests to `omniscli.lbs` directly? I can see where #9 solves that specific dependency, which is useful in itself, but I don't follow how it helps with application testing.

**Comment by Frogli** [comment]
No I do not add tests to the omniscli.lbs. Eg I have a production library named omniSql.lbs and a test library omniSql_test.lbs. I think I will give the omnis-launcher project a try. Thanks for the suggestion!
