### ISSUE TITLE
[Question:] Is omniscli also working with Omnis Studio v. 4

### ISSUE THREAD

**Issue by blu-IT** [suransys/omniscli#6]
Hello,

is _omniscli_ also working with versions of Omnis Studio prior than v. 8 (**here: v. 4 !**)?

Thanks!

Regards,

**Comment by barkingfoodog** [comment]
No, omniscli requires Studio 8 or later. We originally developed it with Studio 5.1 and open-sourced it under 8. We've been using it with 10.0 and 10.1.

You could try getting omniscli working in v4. The scripts in `bin` shouldn't be affected by the Omnis version, although they assume a split installation with application data under the user's home folder. That was added in Studio 4 for Windows, IIRC, but not macOS. It's the library that will definitely need some hacking.

A likely sticking point is the `getenv()` function that returns the `OMNISCLI_ARGUMENTS` environment variable. The scripts use this to pass command-line arguments to Omnis. I don't think `getenv()` existed in Studio 4. You could use another mechanism, like writing to a known file or making some other call to the operating system to get that environment variable. Although it may be out of scope.

There was/is a `sys()` call to get arguments passed to the Omnis executable. We used that back with Studio 5.1 but moved to the environment variable in Studio 8. I think it was just cleaner, and Omnis also wanted an initial parameter of a library to start that we didn't use. IIRC passing `""` bypassed this.

Even earlier back (Studio 3, I think) we used the ultra-thin client to control Omnis from a command line using HTTP. This was always a bit clunky, though, since the app had to be started separately and its lifespan managed outside the HTTP call. The CLI approach was much more seamless once we built it.

**Comment by blu-IT** [comment]
Hi,

thanks for your quick reply and your feedback!

OK, I will give it a try and report as soon as I have some results.
I was looking for possibilities to monitor _Omnis Server_ if still running etc. and so I found omnis-cli that seems very helpful to me in combination with e.g. Nagios.

Regards

**Comment by barkingfoodog** [comment]
You're welcome!

We have a couple Omnis instances running to serve reports via ultra-thin. We monitor their status using nagios by:
1. Making an HTTP call to the server and assert the response is valid
1. Checking processes on the machine and ensue Omnis is up

omniscli might not be the best tool for monitoring as it is designed to fire up Omnis, do some work, then exit Omnis. If you have a persistent server that should stay running I'd use a remote task that can respond to an HTTP request with a heartbeat "system ok".

Alex
